version: "3.8"

services:
  mongodb:
    image: mongo:7.0.0
    restart: always
    container_name: mongodb
    networks:
      - mongo_network
    ports:
      - ${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  app:
    image: node:20.17.0
    networks:
      - mongo_network
    working_dir: /var/www/app
    container_name: app
    command: bash -c "npm i && npm run start:dev"
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    volumes:
      - .:/var/www/app
    depends_on:
      - mongodb

networks:
  mongo_network:
    driver: bridge
    name: mongo_network

volumes:
  data:
